name: Terragrunt Plan

on:
  pull_request:
    paths:
      - "**/*.json"
      - "**/*.tf"
      - "**/*.hcl"
jobs:
  terragrunt-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1
      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5
          terraform_wrapper: false
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.52.3
      - name: Determine Changed Directories
        id: changed_dirs
        run: |
          CHANGED_DIRS=$(git diff --name-only HEAD^ HEAD -- 'AWS/**/*.hcl' | xargs -n 1 dirname | sort | uniq)
          echo "::set-output name=dirs::$CHANGED_DIRS"
      - name: Terragrunt Plan
        run: |
          for dir in ${{ steps.changed_dirs.outputs.dirs }}
          do
            pushd $dir
            echo "Running terragrunt plan in $dir"
            terragrunt plan --terragrunt-non-interactive
            dirs
            popd
          done
